name: Upload from Link

on:
  workflow_dispatch:    # اجرای دستی از طریق دکمه

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download file from URL
        run: curl -L -o myfile.zip "https://s2.dlserfes.info/dl20/series/2026/Stranger.Things.Tales.From.85/S01/720/Stranger.Things.Tales.From.85.S01E01.720p.WEB-DL.FilmKio.mkv?md5=_qpu1JQMCoYJw3rb5Tl4Ug&u=0&expires=1777920671"
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: myfile.zip
          tag_name: v1.0.0   # نام تگ Release
          token: ${{ secrets.GITHUB_TOKEN }}
