name: Upload from Link

on:
  workflow_dispatch:    # اجرای دستی از طریق دکمه

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download file from URL
        run: curl -L -o myfile.zip "https://filesto.firezone.space/download/gAAAAABp-FVsy0AlMZuiTW65IlVFBFF53oE-jvuMgXEr4olAw-lrDB7fWyQ6QlXFAgLIOxDUuq1rc36sZPoErCdEUFu36khdgEEmDe2KCJ-LMyzyzP6aFMNuK0VfjDYGNvc0Ii1M7oBqYOGKmpLljW3nO0BnL6GQfOwK3NEL7sLL7xneL8WZQ15Wmk_dTQabtrepqzdV9gWSHJWqwG1OaxR94vXEYx_SUbUqYxTgitChgIsqU2kPNthU3XuA1Ba94W4i1ExGQzke"
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: myfile.zip
          tag_name: v1.0.0   # نام تگ Release
          token: ${{ secrets.GITHUB_TOKEN }}
