name: Upload from Link

on:
  workflow_dispatch:    # اجرای دستی از طریق دکمه

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download file from URL
        run: curl -L -o myfile.zip "http://dt3.tdmm2.ir/movies-dt3/serie/04/Invincible/fasl4/Invincible.S04E01.480p.WEB-DL.x264-BMB.SoftSub.BMB.B8E92CEB.mkv?expire=1777963388&hash=Nqa6ilEGDb2bWdTijUoZbA"
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: myfile.zip
          tag_name: v1.0.0   # نام تگ Release
          token: ${{ secrets.GITHUB_TOKEN }}
